### ISSUE TITLE
Data cleaning and removing the bias using sub and super sampling

### ISSUE THREAD

**Issue by sorba160** [DSCKGEC/NASA-Collision-Detection#1]
The data set is biased . So the accuracy level is not good . Need help for cleaning the data and removing the bias. There are 8840 values for hazardous objects and the remaining 81995 values for non-hazardous objects which clearly indicates a large imbalance in the dataset.
To remove bias preferably sub and super sampling is needed.

**Comment by sorba160** [comment]
@srini047  are you interested to work here ? Please comment to get assigned .

**Comment by srini047** [comment]
> @srini047  are you interested to work here ? Please comment to get assigned .

Sure. Would like to work on this.

Wasn't aware of the redundancy in the issue. Would keep in mind next time.

**Comment by sorba160** [comment]
Ok. You are assigned @srini047

**Comment by sorba160** [comment]
@srini047 today is the last day for the competition . Submit your work as soon as possible.

**Comment by srini047** [comment]
> @srini047 today is the last day for the competition . Submit your work as soon as possible. 

Sure.
