### ISSUE TITLE
Overcoming Imbalance in Dataset

### ISSUE THREAD

**Issue by srini047** [DSCKGEC/NASA-Collision-Detection#16]
**Is your feature request related to a problem? Please describe.**
There are 8840 values for hazardous objects and the remaining 81995 values for non-hazardous objects which clearly indicates a large imbalance in the dataset.

**Describe the solution you'd like**
So using the concept of upsampling(hazardous)  or downsampling(non-hazardous) whichever solution produces the optimal results to be implemented.

**Additional context**
Using the ```from sklearn.utils import resample``` will produce the code.

**Comment by sorba160** [comment]
Ok here also I am assigning you. Do the necessary changes. Thank you for the issue. @srini047

**Comment by abhishak3** [comment]
isn't it a duplicate of issue #1

**Comment by sorba160** [comment]
Actually you are right @abhishak3

**Comment by abhishak3** [comment]
Yeah, so maybe close the other issue or this one just to avoid the confusion. Just in case!

**Comment by sorba160** [comment]
I have closed this one . Thanks
