### ISSUE TITLE
Data visualization 

### ISSUE THREAD

**Issue by sorba160** [DSCKGEC/NASA-Collision-Detection#2]
Data visualization is not done . Need help For data visualization for better impact . Any kind of graphs or plotting is preferable.  Plot histogram or density graph or Box Plot to visualize, "est_diameter_min", "est_diameter_max", "relative_velocity", "miss_distance" , "absolute_magnitude". of the data set.

**Comment by sorba160** [comment]
This is not the proper way to work @abhishak3 . At first you have to comment under the issue if you can solve it . Then we will assign you for the work . Then only you can submit your work by creating pull request. Follow the way , other wise your pull request will be rejected irrespective of good or bad work.

**Comment by abhishak3** [comment]
I am sorry and I didn't know the procedure.
Please leave me on this one and Can you check out the PR I have made?
Thanks.
P.S. Can you please mention the procedures as a precaution for the new participants so that they don't make the same mistake.

**Comment by sorba160** [comment]
No problem but follow the work process I have mentioned in the previous comment ( please read properly) and then make PR. Please delete your previous PR , follow the process as I told and make PR.

**Comment by abhishak3** [comment]
Can you please assign it to me?

**Comment by abhishak3** [comment]
I'll be using multiple histograms to visualize different columns provided in the dataset.
It can be done with one command `DataFrame.hist(bins=bins, figsize=(breadth, length))`

**Comment by sorba160** [comment]
Ok I am assigning you @abhishak3 . But please remember the work process for further,
