### ISSUE TITLE
Univariate and bivariate analysis

### ISSUE THREAD

**Issue by sorba160** [DSCKGEC/NASA-Collision-Detection#4]
Univariate statistics summarize only one variable at a time. Bivariate statistics compare two variables. Need help to do this for this data set .  And show the output . And explain the importance of it.

**Comment by abhishak3** [comment]
I would like to take up this issue. Can I?

**Comment by sorba160** [comment]
Sure . I am assigning you. All the best for your work. @abhishak3

**Comment by sorba160** [comment]
@abhishak3 please resolve the conflict in PR.  Otherwise it can't be merged.
