### ISSUE TITLE
Apply Logistic Regression

### ISSUE THREAD

**Issue by sorba160** [DSCKGEC/NASA-Collision-Detection#6]
Apply Logistic Regression for supervised machine learning for the prediction. In the output accuracy  and error calculation must be printed. Show the accuracy is improved or not . Since the outcome is a probability, the dependent variable is bounded between 0 and 1.

**Comment by KewlShubh** [comment]
I would like to work on this issue. Kindly grant me access :)

**Comment by sorba160** [comment]
Ok I am assigning you  @KewlShubh . All the best for your work.
