### ISSUE TITLE
Apply Random Forest Classifier

### ISSUE THREAD

**Issue by sorba160** [DSCKGEC/NASA-Collision-Detection#7]
Apply Random Forest Classifier for supervised machine learning for the Classification. In the output accuracy and confusion matrix must be printed. Show the accuracy is improved or not . A random forest is a meta estimator that fits a number of decision tree classifiers on various sub-samples of the dataset and uses averaging to improve the predictive accuracy and control over-fitting. Do the necessary plotting to tally between hazardous and non hazardous nearest earth objects.

**Comment by srini047** [comment]
I would like to work on this issue. Kindly assign me.

**Comment by sorba160** [comment]
Ok I'm assigning you. All the best for your work.

**Comment by sorba160** [comment]
Have you not done any kind of plotting for visualization. ? @srini047

**Comment by srini047** [comment]
> Have you not done any kind of plotting for visualization. ? @srini047 

Nope. Let me do a visualisation.

**Comment by sorba160** [comment]
Ok please do @srini047

**Comment by sorba160** [comment]
@srini047 please resolve conflict in the PR. Other wise I can't merge it.

**Comment by srini047** [comment]
> @srini047 please resolve conflict in the PR. Other wise I can't merge it.

Sure. I would like to get some help if I am unable to resolve it.
